# Question:
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#       1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def even_fibs_below(x: int) -> int:
  last_2_fibs = [1, 2]
  sum_of_even = 0

  while last_2_fibs[-1] < x:
    if last_2_fibs[-1] % 2 == 0:
      sum_of_even += last_2_fibs[-1]
      last_2_fibs = [last_2_fibs[-1], sum(last_2_fibs)]

  return sum_of_even
