# Question:
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def evenFibsBelow(x:int)->int:
    last2Fibs=[1, 2]
    sumOfEven=0
    while last2Fibs[-1]<x:
        if last2Fibs[-1]%2==0:
            sumOfEven+=last2Fibs[-1]
        last2Fibs=[last2Fibs[-1],sum(last2Fibs)]
    return sumOfEven

if __name__ == '__main__':
    print(evenFibsBelow(4000001))
